spring:
  # 消息总线相关配置
  rabbitmq:
    host: ${RABBITMQ.HOST:192.168.1.172}
    port: ${RABBITMQ.PORT:5672}
    username: ${RABBITMQ.USERNAME:guest}
    password: ${RABBITMQ.PASSWORD:guest}
  cloud:
    bus:
      enabled: true
    trace: 
      enabled: true # 开启消息跟踪 
  application:
    name: adminserver
  zipkin:
    base-url: ${ZIPKIN.URL:http://192.168.1.173:9411}
server:
  port: 8889
eureka:
  instance:
    ip-address: 192.168.1.173
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${DEFAULTZONE:http://192.168.1.172:8080/eureka/,http://192.168.1.173:8080/eureka/}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: "*"
