server:
  port: 9901
spring:
  application:
    name: storage-baseinfo
  # 服务链路追踪
  zipkin:
    base-url: ${ZIPKIN.URL:http://192.168.1.173:9411}
  boot:
    admin:
      client:
        url: ${ADMIN.URL:http://192.168.1.173:8889}
  rabbitmq:
    host: ${RABBITMQ.HOST:192.168.1.172}
    port: ${RABBITMQ.PORT:5677}
    username: ${RABBITMQ.USERNAME:guest}
    password: ${RABBITMQ.PASSWORD:guest}
  cloud:
    bus:
      enabled: true
    trace: 
      enabled: true # 开启消息跟踪     
  # 配置数据库信息
  datasource:
    # 数据源配置
    username: postgres
    password: 123456
    url: jdbc:postgresql://192.168.1.172:5432/zegobirdWMS_Basis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      connection-test-query: select 1
eureka:
  instance:
    ip-address: 192.168.1.174
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${DEFAULTZONE:http://192.168.1.172:8080/eureka/,http://192.168.1.173:8080/eureka/}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
swagger:
  auth:
    server: http://192.168.1.172:8886/zegooauth/oauth/token

mybatis-plus:
# spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  oauth2:
    resource:
      id: oauth2-server
      user-info-uri: http://192.168.1.172:8886/zegooauth/api/member
      prefer-token-info: false
apiseller:
  api:
    queryStore: ${QUERYSTORE.API:http://192.168.10.171:8888/apiseller/api/queryStroe}
    storeType: 1,2,3,7,8
